//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controllers_CustomerController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers_CustomerController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PragWebApp.Resources.Controllers.CustomerController", typeof(Controllers_CustomerController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CustomerEntity_Created {
            get {
                return ResourceManager.GetString("CustomerEntity_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CustomerEntity_Description {
            get {
                return ResourceManager.GetString("CustomerEntity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string CustomerEntity_Email {
            get {
                return ResourceManager.GetString("CustomerEntity_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail is required field.
        /// </summary>
        public static string CustomerEntity_EmailRequired {
            get {
                return ResourceManager.GetString("CustomerEntity_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string CustomerEntity_FirstName {
            get {
                return ResourceManager.GetString("CustomerEntity_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required field.
        /// </summary>
        public static string CustomerEntity_FirstNameRequired {
            get {
                return ResourceManager.GetString("CustomerEntity_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string CustomerEntity_LastName {
            get {
                return ResourceManager.GetString("CustomerEntity_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required field.
        /// </summary>
        public static string CustomerEntity_LastNameRequired {
            get {
                return ResourceManager.GetString("CustomerEntity_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string CustomerEntity_PhoneNumber {
            get {
                return ResourceManager.GetString("CustomerEntity_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required field.
        /// </summary>
        public static string CustomerEntity_PhoneNumberRequired {
            get {
                return ResourceManager.GetString("CustomerEntity_PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mails.
        /// </summary>
        public static string CustomerEntity_SendEmails {
            get {
                return ResourceManager.GetString("CustomerEntity_SendEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMSs.
        /// </summary>
        public static string CustomerEntity_SendSmss {
            get {
                return ResourceManager.GetString("CustomerEntity_SendSmss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CustomerEntity_Status {
            get {
                return ResourceManager.GetString("CustomerEntity_Status", resourceCulture);
            }
        }
    }
}
